---
title: "Untitled"
output: html_document
date: "2023-01-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Set-Up ##
- I have this version of R language installed as of 4 Jan 2023: R VERSION 4.2.2 Patched (2022-11-10 r83330). 

```{r}
set.seed(1999)
options(repos = c(binary = "https://packagemanager.rstudio.com/cran/__linux__/jammy/2023-01-04",
                  source = "https://packagemanager.rstudio.com/cran/2023-01-04",
                  CRAN = "https://cloud.r-project.org"))


# install.packages("BiocManager")
# BiocManager::install(version = "3.16") #this version of BiocManager works with R version 4.2.2
library(BiocManager) # v1.30.19

# BiocManager::install(c("agilp", "limma", "oligo", "GEOquery", "dplyr", "stringr", "ggplot2", "reshape2", "tidyverse", "gplots"), ask=F)
library(agilp)            # v3.30.0
library(limma)            # v3.54.1
library(oligo)            # v1.62.2
library(GEOquery)         # v2.66.0
library(dplyr)            # v1.1.0
library(tidyr)            # v1.3.0
library(stringr)          # v1.5.0
library(ggplot2)          # v3.4.0
library(reshape2)         # v1.4.4
library(tidyverse)        # v.3.2
library(gplots)           # v3.1.3
library(patchwork)

#install.packages("ggvenn")  
library(ggvenn)
install.packages("UpSetR")  
library(UpSetR)

#install.packages("car")  
library(car)

#BiocManager::install("convert") #for converting MAList to Eset object
library(convert)          # v.74.0

#install.packages("dynutils")
library(dynutils)         # v1.0.11

#probe filtering
#BiocManager::install("genefilter")
library(genefilter)    # v1.80.3


#### Annotation packages

#BiocManager::install("biomaRt")
library(biomaRt)         # v2.54.0


#BiocManager::install(c("AnnotationHub", "Homo.sapiens","Organism.dplyr"))  #https://www.bioconductor.org/packages/release/workflows/vignettes/annotation/inst/doc/Annotation_Resources.html#introduction
#library(AnnotationHub)
#library(Homo.sapiens)
#library(Organism.dplyr)


#BiocManager::install("org.Hs.eg.db")

#### Annotate package for reannotation
#BiocManager::install("annotate")
#library(annotate)

#BiocManager::install("hgug4112a.db") #annotation package for the microarray platform used - catalog code of microarray is G4112F
library(hgug4112a.db)

#### rePROBE method of annotation  --- didnt use
#BiocManager::install("Rbowtie")
#library(Rbowtie)
#devtools::install_github("friederhadlich/rePROBE")
#library(rePROBE)


#BiocManager::install("sva")
library(sva)           # v3.46.0

#BiocManager::install("maSigPro")
#library(maSigPro)      # v1.70.0
 


#checking for batch effect
#install.packages("~/Downloads/gPCA_1.0.tar.gz", repos = NULL, type = "source")
library(gPCA)          # v1.0  - to install must download packages files from archive.



#quality check package
#BiocManager::install("arrayQualityMetrics")
library(arrayQualityMetrics)

```

```{r}

```

